# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-06 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient_is_visited'),
    ]

    operations = [
		migrations.RenameField('Patient', 'doctor', 'Teacher'),
    ]
